name: thankxdriver
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.18+18

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  overlay_support: ^1.0.2
  shared_preferences: ^0.5.6+1
  device_info: ^0.4.1+4
  sliding_up_panel: ^1.0.2
  tuple: ^1.0.3
  dio: ^3.0.9
  intl: ^0.16.1
  rxdart: ^0.18.0
  flutter_spinkit: ^4.1.1+1
  flutter_mailer: ^0.4.3
  image_picker: 0.6.6+1
  google_maps_flutter:
  google_places_picker: 2.1.0+2
#  extended_image: 0.7.1
  extended_image:
    git:
      url: https://github.com/jonataslaw/extended_image.git
  flutter_slidable: ^0.5.4
  geolocator: ^5.3.1
  webview_flutter:
    path: ../webview_flutter
  url_launcher: ^5.4.2
  connectivity: ^0.4.6+2
#  ^0.4.8+6
  share: ^0.6.3+6
  smooth_page_indicator: ^0.1.5
  smooth_star_rating: ^1.1.0+1
  file_picker: ^1.2.0
  after_layout: ^1.0.7+2
  firebase_messaging:
#    path: ../firebase_messaging
  permission_handler: 4.3.0
  flutter_cupertino_date_picker: any
#  flutter_cupertino_date_picker_fork: ^1.0.3
  location: 3.0.2
  flutter_image_compress: 0.6.8
  path_provider: 1.6.7
  flutter_exif_rotation: 0.2.7
#  flutter_polyline_points: ^0.1.0
#  google_map_polyline: ^0.0.2
  photo_view: ^0.10.3
  flutter_image_slideshow: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: SfCompactMedium
      fonts:
        - asset: assets/font/SF-Compact-Rounded-Medium.ttf
    - family: SfCompactRegular
      fonts:
        - asset: assets/font/SF-Compact-Rounded-Regular.ttf
    - family: SfCompactSemiBold
      fonts:
        - asset: assets/font/SF-Compact-Rounded-Semibold.ttf
    - family: SfProDisplayBold
      fonts:
        - asset: assets/font/SFProDisplay-Bold.ttf
    - family: SfProDisplayLight
      fonts:
        - asset: assets/font/SFProDisplay-Light.ttf
    - family: SfProDisplayMedium
      fonts:
        - asset: assets/font/SFProDisplay-Medium.ttf
    - family: SfProTextLight
      fonts:
        - asset: assets/font/SFProText-Light.ttf
    - family: SfProTextMedium
      fonts:
        - asset: assets/font/SFProText-Medium.ttf
    - family: SfProTextRegular
      fonts:
        - asset: assets/font/SFProText-Regular.ttf
    - family: SfProTextSemibold
      fonts:
        - asset: assets/font/SFProText-Semibold.ttf
    - family: SfProTextBold
      fonts:
        - asset: assets/font/SFProText-Bold.ttf
    - family: HelveticaNeueRegular
      fonts:
        - asset: assets/font/Helvetica-Neue-Regular.ttf
    - family: HelveticaNeueLight
      fonts:
        - asset: assets/font/HelveticaNeue-Light.ttf
    - family: SfProDisplayRegular
      fonts:
        - asset: assets/font/SfProDisplay-Regular.ttf
  assets:
    - assets/images/aboutus.png
    - assets/images/add.png
    - assets/images/add_hover.png
    - assets/images/awaiting_receiver.png
    - assets/images/back_arrow.png
    - assets/images/calendar.png
    - assets/images/call.png
    - assets/images/circle.png
    - assets/images/checkbox.png
    - assets/images/close.png
    - assets/images/cotacts.png
    - assets/images/user.png
    - assets/images/cotactus.png
    - assets/images/down_arrow.png
    - assets/images/down_arrow_unselected.png
    - assets/images/drop.png
    - assets/images/drop_hover.png
    - assets/images/home.png
    - assets/images/info_icon.png
    - assets/images/info_selected.png
    - assets/images/item_large.png
    - assets/images/item_medium.png
    - assets/images/item_small.png
    - assets/images/lock.png
    - assets/images/logo.png
    - assets/images/me.png
    - assets/images/me_hover.png
    - assets/images/no_switch.png
    - assets/images/notifications.png
    - assets/images/office.png
    - assets/images/order.png
    - assets/images/order_hover.png
    - assets/images/order_icon_1.png
    - assets/images/order_icon_2.png
    - assets/images/order_icon_3.png
    - assets/images/order_icon_4.png
    - assets/images/order_icon_5.png
    - assets/images/orders.png
    - assets/images/orders_hover.png
    - assets/images/other.png
    - assets/images/payment.png
    - assets/images/payment_card.png
    - assets/images/pickup_2.png
    - assets/images/pickup_2_hover.png
    - assets/images/pickup_3.png
    - assets/images/pickup_3_hover.png
    - assets/images/privacypolicy.png
    - assets/images/profile.png
    - assets/images/radio_button_checked.png
    - assets/images/radio_button_unchecked.png
    - assets/images/saved_home.png
    - assets/images/savedaddresses.png
    - assets/images/search_icon.png
    - assets/images/termsofuse.png
    - assets/images/uncheckbox.png
    - assets/images/walk_1.png
    - assets/images/walk_2.png
    - assets/images/Walk_3.png
    - assets/images/Walk_4.png
    - assets/images/yes_switch.png
    - assets/images/location_point.png
    - assets/images/add_icon.png
    - assets/images/close_icon.png
    - assets/images/image_placeholder.png
    - assets/images/notification_icon.png
    - assets/images/profile_picture_placeholder.png
    - assets/images/drop_point.png
    - assets/images/flag_icon.png
    - assets/images/flag.png
    - assets/images/flag_active.png
    - assets/images/tickmark_icon.png
    - assets/images/map.png
    - assets/images/map_active.png
    - assets/images/right_arrow.png
    - assets/images/plus_payment.png
    - assets/images/payment_icon.png
    - assets/images/switch_on.png
    - assets/images/switch_off.png
    - assets/images/delivered_flag.png
    - assets/images/listview_icon.png
    - assets/images/deliver.png
    - assets/images/my_jobs_hover.png
    - assets/images/download_icon.png
    - assets/images/upload_icon.png
    - assets/images/mapview_icon.png
    - assets/images/reviews.png
    - assets/images/tax_information.png
    - assets/images/wallet.png
    - assets/images/star.png
    - assets/images/star_gray.png
    - assets/images/plus_icon.png
    - assets/images/change_password.png
    - assets/images/swipe_left.png
    - assets/images/swipe_right.png
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
